[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc = '0.8.10'
eth_rpc_url = "http://localhost:8545"

[profile.op]
eth_rpc_url = "https://mainnet.optimism.io"

[profile.base]
eth_rpc_url = "https://mainnet.base.org"

[profile.zora]
eth_rpc_url = "https://rpc.zora.energy"

[profile.op-goerli]
eth_rpc_url = "https://goerli.optimism.io"

[profile.base-goerli]
eth_rpc_url = "https://goerli.base.org"

[profile.zora-goerli]
eth_rpc_url = "https://testnet.rpc.zora.energy"

[profile.mode-sepolia]
eth_rpc_url = "https://sepolia.mode.network"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config